baseURL = "https://earnonlinemoney.org/"
title = "Generate Income Online"
theme = "ramem"
languageName = "En"
languageCode = "en-us"
pagination.pagerSize = "10"
summaryLength = "20"
enableRobotsTXT = true

[minify]
  minifyOutput = true

[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[imaging]

quality = 90

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[sitemap]
  changeFreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
taxonomiesExcludedFromSitemap = ["tags"]
