######################## default configuration ####################
baseURL = "https://earnonlinemoney.org/"
title = "Earn Money Online Free | Side Hustles | Online Jobs"
theme = "ramem"
languageName = "En"
languageCode = "en-us"
pagination.pagerSize = "10"
summaryLength = "20"
googleAnalytics = "G-PNQXNMRNBD"
disqusShortname = "disqus_afGZDYYvBY"
enableRobotsTXT = true



############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]

quality = 90

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
  [markup.goldmark.renderer]
    unsafe = true

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


############################ sitemap  ###########################
[sitemap]
  changeFreq = 'daily'
  filename = 'sitemap.xml'
  priority = 5

############################ exclude from sitemap  ###########################
[params]
taxonomiesExcludedFromSitemap = ["tags", "categories"]
