favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "150x"
logo_text = "Generate Income Online"
navbar_fixed = false
description = "Want to generate income online? Find free ways to earn money via side hustles, remote online jobs, or home-based business opportunities. Pursue financial freedom now!"
author = "Dejuan Jones"
image = "images/logo.png"
contact_form_action = "https://formspree.io/f/xdoreeqg"
search = true
## Twitter Cards
twitterSite = "@moneyonline_fre"
twitterCreator = "@moneyonline_fre"
alternateName = "Earn Money Online"
authorURL= "https://earnonlinemoney.org/about"

categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
previous_button = "Previous"
next_button = "Next"
related_posts = "Previous Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]

footer_content = "Empowering you with the best ideas to earn online—because financial freedom starts with the right knowledge."

theme_copyright = true
copyright = "© 2018-2025"

error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

[banner]
enable = true
title_large = "Generate Income Online"
title_small = "Side Hustles, Online Jobs & Passive Income Ideas"
content = "Welcome! Your journey to earning money online starts now. Here you can learn how to make money from home, start your own business, and build financial freedom. From online jobs and side hustles to entrepreneurial ideas and passive income opportunities—there’s something here for everyone, including students, stay-at-home moms, and invdividuals with no experiencene. No matter where you live—Africa, Panama, South America, Asia, the UK, or beyond—opportunities to earn are everywhere, and we are here to help you find them."

[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[widgets]
sidebar = ["categories", "newsletter"]

[subscription]
enable = false
newsletter_title = "Newsletter"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Sign in"

mailchimp_form_action = "https://gmail.us17.list-manage.com/subscribe/post?u=3392b2d612de88ac6644ca414&amp;id=3ecf0e3fef&amp;f_id=00e55de0f0"
mailchimp_form_name = "b_3392b2d612de88ac6644ca414_3ecf0e3fef"


[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/earnmoneynowonline"
url = "https://www.facebook.com/earnmoneynowonline"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/moneyonline_fre"
url = "https://twitter.com/moneyonline_fre"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/earn-money-online-free"
url = "https://www.linkedin.com/company/earn-money-online-free"
