favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "150x"
logo_text = "Earn Money Online"
navbar_fixed = false
description = "Ultimate guide to earn money online free. Find legitimate side hustles, passive income ideas, online jobs & more. Learn how to get paid from home today."
author = "Dejuan Jones"
image = "images/logo.png"
contact_form_action = "https://formspree.io/f/xdoreeqg"
search = true
## Twitter Cards
twitterSite = "@moneyonline_fre"
twitterCreator = "@moneyonline_fre"

schemaLocale = "en-US"

categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
explore_button = "Explore"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]
about_widget_content = "Find Us On Social Media."

footer_content = "Empowering you with the best ideas to earn online—because financial freedom starts with the right knowledge."

theme_copyright = true
copyright = "© 2018-2025"

error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

[preloader]
enable = false
preloader = ""

[banner]
enable = true
title_large = "Earn **Money** Online"
title_small = "Passive Income Ideas"
image = "images/cash-banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Welcome! Your journey to earning money online starts now. Here you can learn how to make money from home, start your own business, and build financial freedom. From online jobs and side hustles to entrepreneurial ideas and passive income opportunities—there’s something here for everyone, including students, stay-at-home moms, and invdividuals with no experiencene. No matter where you live—Africa, Panama, South America, Asia, the UK, or beyond—opportunities to earn are everywhere, and we are here to help you find them."

[advertisement]
image = "images/income-online.jpg"
link = "/"

[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post

[subscription]
enable = false
newsletter_title = "Newsletter"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Sign in"

mailchimp_form_action = "https://gmail.us17.list-manage.com/subscribe/post?u=3392b2d612de88ac6644ca414&amp;id=3ecf0e3fef&amp;f_id=00e55de0f0"
mailchimp_form_name = "b_3392b2d612de88ac6644ca414_3ecf0e3fef"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/earnmoneynowonline/"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/moneyonline_fre/"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/earn-money-online-free/"
